## CSCI-467 Discussion (Week 1)

### Rules

1. Please read the instructions and problem prompts **carefully**.
2. This lab is to give you some basic APIs of numpy, pandas and scikit-learn. The lab is to be done individually. You may talk to your fellow classmates about general issues ("Remind me again: Which API should I used for doing group by operation to a data set") but about the specifies of how to do these exercises.
3. Along with a similar vein, you can ask the TA for help, but ask questions about **concepts** but not ask the TA to help you debug your code. The TA is here to help, but not to do the work for you.
4. You are welcome to use the class resources and the Internet.
5. Playing with variations. Solve one problems, and then copy the code to a new cell and play around with it. Doing this is the single most important thing when learning programming.
6. This lab will not be graded but the content is highly related to your future programming assignments. So, treat it wisely.
7. All the content having been gone though in the week 1 discussion is just a snapshot of the most basic concepts. **You need to keep study more about Git, GitHub, Pandas, Numpy and Scikit-Learn in order to finish your programming assignments successfully.**
8. Have fun!

### Setup Development Environment

There are many ways to setup the environment. But, I do recommend a simple idea that is using the Anaconda, which is a pre-build python environment with bundles of useful packages.

**To download the Anaconda, go to the following website:
https://www.anaconda.com/distribution/**. Download the correct version based on your operating system and install it step by step.

Then, **configure your PATH environment variable** to make the conda command work. The following command is an easy way to test whether your configuration is correct. If it is, you will see something as like as the sample output.

> **command:**
>
> conda --version
>
> **sample output:**
>
> conda 4.6.12

**Finally, download this jupyter notebook file,** then change the working directory to where its location in terminal, and type the following command to open the jupter notebook and finish the lab.

> **command:** 
> jupyter notebook

### Pandas

#### The read_csv() Method

First, read the documentation about the *read_csv()* method in Pandas (https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html). Then, try to read data from file Salaries.csv to a dataframe, make the column playerID in the csv file as the index column and the first row as the header. Also, skip the second row when reading the file.

In [116]:
import pandas as ps
df = ps.read_csv("salaries.csv", header = 0, index_col = 3, skiprows = [1, 2])
df.head() #to only pring the first 5 rows for neatness

yearID teamID lgID  salary
playerID                             
bedrost01    1985    ATL   NL  550000
benedbr01    1985    ATL   NL  545000
campri01     1985    ATL   NL  633333
ceronri01    1985    ATL   NL  625000
chambch01    1985    ATL   NL  800000

#### Indexing and Selecting Data

Select the id of the players who are registered in ATL and HOU and whose salary is higher than one million.

In [23]:
df.loc[(df.teamID == 'ATL') | (df.teamID == 'HOU') & (df.salary > 1000000)]

3315763.3897464117

#### The describe() Method

Calculate the standard Deviation, first quartile, medium, third quartile, mean, maximum, minimum of the salary in team ATL.

In [87]:
df_atl = df.loc[(df.teamID == 'ATL')]
df_atl.describe()['salary'][['std', '25%', '50%', '75%', 'mean', 'max', 'min']]

std     3.434320e+06
25%     3.000000e+05
50%     6.000000e+05
75%     2.400000e+06
mean    2.207749e+06
max     1.606180e+07
min     6.000000e+04
Name: salary, dtype: float64

#### The iterrows() Method

Create a Python dictionary object whose keys are the headers of the dataframe created in the read_csv() exercise and values are Python list objects that contain data corresponding to the headers. (Here, use the iterrows method to iterate each row of the dataframe and copy it to a dictionary. However, there is a easier way. Learn how the to_dict() method works by yourself later)

In [153]:
import numpy as np

mydata_dict = {}
for i, r in df.iteritems():
    mydata_dict[i] = r
    
#print(mydata_dict.keys())
#print(mydata_dict.values())
print(mydata_dict)

#things that make think I did this wrong... 
#one: playerID is skipped as a header and included as part of data because it was set as the index column
#two: playerID data is included in value data, seems helpful but maybe not what is asked for here?

{'yearID': playerID
bedrost01    1985
benedbr01    1985
campri01     1985
ceronri01    1985
chambch01    1985
             ... 
treinbl01    2015
ugglada01    2015
werthja01    2015
zimmejo02    2015
zimmery01    2015
Name: yearID, Length: 25574, dtype: int64, 'teamID': playerID
bedrost01    ATL
benedbr01    ATL
campri01     ATL
ceronri01    ATL
chambch01    ATL
            ... 
treinbl01    WAS
ugglada01    WAS
werthja01    WAS
zimmejo02    WAS
zimmery01    WAS
Name: teamID, Length: 25574, dtype: object, 'lgID': playerID
bedrost01    NL
benedbr01    NL
campri01     NL
ceronri01    NL
chambch01    NL
             ..
treinbl01    NL
ugglada01    NL
werthja01    NL
zimmejo02    NL
zimmery01    NL
Name: lgID, Length: 25574, dtype: object, 'salary': playerID
bedrost01      550000
benedbr01      545000
campri01       633333
ceronri01      625000
chambch01      800000
               ...   
treinbl01      512800
ugglada01      507500
werthja01    21000000
zimmejo02    16500000
zimmery01    14

#### Create Dataframe Using the Constructor

Read the documentation: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html#pandas.DataFrame and create a dataframe using pd.DataFrame from the dictionary created in the iterrows() exercise. Change the header to "a", "b", "c", ... at creation time.

In [182]:
new_data = ps.DataFrame(mydata_dict).rename(columns={'yearID': 'a', 'teamID': 'b', 'lgID': 'c', 'salary': 'd'})
new_data

a    b   c         d
playerID                          
bedrost01  1985  ATL  NL    550000
benedbr01  1985  ATL  NL    545000
campri01   1985  ATL  NL    633333
ceronri01  1985  ATL  NL    625000
chambch01  1985  ATL  NL    800000
...         ...  ...  ..       ...
treinbl01  2015  WAS  NL    512800
ugglada01  2015  WAS  NL    507500
werthja01  2015  WAS  NL  21000000
zimmejo02  2015  WAS  NL  16500000
zimmery01  2015  WAS  NL  14000000

[25574 rows x 4 columns]

### Numpy

Quick start: https://www.numpy.org/devdocs/user/quickstart.html

Numpy axes explaination: https://www.sharpsightlabs.com/blog/numpy-axes-explained/

#### The np.array Method

Example 1:

```python
ls = [1, 2, 3]
arr = np.array(ls)
```

Example 2:
```python
>>> np.array([[1, 2], [3, 4]])
array([[1, 2],
       [3, 4]])
```

Now, create a 2-dimensional Python list object, then convert it to a Numpy array object.

In [191]:
mylist = ([['A', 'a'], 
          ['B', 'b']])
nparray = np.array(mylist)
print(nparray)

AttributeError: 'list' object has no attribute 'ndim'

#### ndarray Objects' Attributes

Play with the **ndim, shape, size, dtype, itemsize and data** attribute.

Example:

```python
>>> arr = np.array([[1, 2], [3, 4]])
>>> arr.ndim
2
```

In [193]:
print('the number of array dimensions:')
print(nparray.ndim)
print('array dimensions shown in tuple data type:')
print(nparray.shape)
print('shows data type of array elements, in this case unicode with a bit length of 1:')
print(nparray.dtype)
print('shows number of elements in array:')
print(nparray.itemsize)
print('points to start of array\'s data:')
print(nparray.data)

the number of array dimensions:
2
array dimensions shown in tuple data type:
(2, 2)
shows data type of array elements, in this case unicode with a bit length of 1:
<U1
shows number of elements in array:
4
points to start of array's data:


#### Dimension of ndarray Ojects

Play with the reshape() and flatten() method.

Example:
```python
>>> arr = np.array([[1, 2], [3, 4]])
>>> arr.flatten()
array([1, 2, 3, 4])
```

In [211]:
arr = nparray.reshape(1,4) ##reshaping to a height of 1 row and width of 4 columns, essentially flattening
print(arr)
print()
arr2 = nparray.flatten() ##flatten method reduces to 1 dimension
print(arr2)
print()
arr3 = nparray.reshape(4,1) ##reshaping array data to a single column and 4 rows
print(arr3)
print()

[['A' 'a' 'B' 'b']]

['A' 'a' 'B' 'b']

[['A']
 ['a']
 ['B']
 ['b']]



#### The Slice Operation of ndarray Objects

Understand how the slice operation works for 1-D array and 2-D array.

Example:

```python
>>> arr = np.array([[1, 2, 3], [3, 4, 6], [7, 8, 9]])
>>> arr[1:]
array([[3, 4, 6],
       [7, 8, 9]])
>>> arr[1:, 0:2]
array([[3, 4],
       [7, 8]])
```

In [227]:
newarr = np.array([[1, 2, 3], 
                   [3, 4, 6], 
                   [7, 8, 9]])
subarr = newarr[2:, 2:]   ##slices array to begin on index 2 on both axes. This results in subarr being the bottom right element
print(subarr)
print()

subarr = newarr[1:, 1:]   ##here the array slices indices 0 on both axes
print(subarr)
print()

subarr = newarr[:2, :2]   ##here, we omit anything in index 2 on both axes
print(subarr)
print()

subarr = newarr[1:2, 1:2] ##here we say to start the sub array only on index 1 on both axes, then cut off 
print(subarr)             ##the array starting at index 2, so the subarray holds only the middle element of this array
print()

[[9]]

[[4 6]
 [8 9]]

[[1 2]
 [3 4]]

[[4]]



## The Calculation of ndarray Objects

Play with the **argmin(), argmax(), min(), max(), mean(), sum(), std(), dot(), square(), sqrt(), abs(). exp(), sign(), mod()** method.

Example:

```python
>>> np.square(array)
array([[ 1,  4,  9],
       [ 9, 16, 36],
       [49, 64, 81]])

```

In [291]:
a = np.array([[ 1, 5,  9],
              [ 9, 4, 36],
              [ 2, 0, 81]])
b = np.array([[ 1, 5,  9],
              [ -9, 4, -36],
              [ 2, 1, -81]])

print(np.argmin(a, axis = 0)) ##returns the index of the minimum value found the axis.
                              ## axis 0 goes down the columns, axis 1 goes down the rows
                              ##here the minimum values are in index 0 of the first and last colums, but index 1 for the center
print()
print(np.argmax(a, axis = 0)) ##argmax is the same as argmin but returns the highest value.
                              ##here the highest value in column index 1 is 5, at the top, or row index 0
print()
print(np.amin(a))             ##returns the minimum value of the whole array
print(np.amin(a, axis = 1))   ##where argmin returns an index, amin returns the element values, also can be called with an axis
print()
print(np.amax(a))             ##same as amin, but returns highest element
print()
print(np.mean(a, axis = 0))   ##computes the mean along a specified axis
print()
print(np.sum(a, axis = 1))    ##computes the sum along a specified axis
print()
print(np.std(a, axis = 1))    ##computes the standard deviation along a specified axis
print()
print(np.dot(a, b))           ##computes dot product between two arrays
print()
print(np.square(a))           ##returns the element-wise squares of the array
print()
print(np.sqrt(a))             ##returns the element-wise square root of the array (non-negative)
print()
print(np.abs(b))              ##returns the element-wise absolute value of the array (non-negative)
print()
print(np.exp(a))              ##calculates the exponential of elements in the array
print()
print(np.sign(b))             ##returns the sign of the number 1 if positive, -1 if negative, 0 if 0
print()
print(np.mod(a, b))           ## returns the element-wise remaindors of division between two arrays


[0 2 0]

[1 0 2]

0
[1 4 0]

81

[ 4.  3. 42.]

[15 49 83]

[ 3.26598632 14.05544576 37.72119946]

[[  -26    34  -900]
 [   45    97 -2979]
 [  164    91 -6543]]

[[   1   25   81]
 [  81   16 1296]
 [   4    0 6561]]

[[1.         2.23606798 3.        ]
 [3.         2.         6.        ]
 [1.41421356 0.         9.        ]]

[[ 1  5  9]
 [ 9  4 36]
 [ 2  1 81]]

[[2.71828183e+00 1.48413159e+02 8.10308393e+03]
 [8.10308393e+03 5.45981500e+01 4.31123155e+15]
 [7.38905610e+00 1.00000000e+00 1.50609731e+35]]

[[ 1  1  1]
 [-1  1 -1]
 [ 1  1 -1]]

[[0 0 0]
 [0 0 0]
 [0 0 0]]


#### Other Important Methods Inside Module Numpy

Play with the arange(), ones(), zeros(), eye(), linspace(), concatenate() method.

Example:

```python
>>> np.eye(3)
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])
```

In [328]:
print(np.arange(1, 10))                  ##returns a half open range between values
print()
print(np.ones((4, 8)))                   ##returns an array of a given shape and type filled with ones!
print()
print(np.zeros((4, 8)))                  ##zeros!
print()
print(np.linspace(7, 142, 7))            ##returns evenly spaced numbers in a given interval with a given range!
print()
print(np.concatenate((a, b), axis = 1))  ##concatenate two different arrays along an axis!


[1 2 3 4 5 6 7 8 9]

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]

[  7.   29.5  52.   74.5  97.  119.5 142. ]

[[  1   5   9   1   5   9]
 [  9   4  36  -9   4 -36]
 [  2   0  81   2   1 -81]]


### Scikit-Learn

The followings are packages (or methods) in Python (Scikit-Learn and Scipy) that will be frequently used in your programming assignment. So, please read carefully.

- Data Preprocessing (https://scikit-learn.org/stable/modules/classes.html#module-sklearn.preprocessing)
    - Standardization: StandardScaler
    - Normalization: MinMaxScaler
    - Quantifing Categorical Features: LabelEncoder. OneHotEncoder
    - Construct Train and Test Set: model_selection.train_test_split
- KNN: KNeighborsClassifier
- Linear Regression: LinearRegression
- Logistic Regression: LogisticRegression, LogisticRegressionCV
- Feature Selection / Model Selection
    - L1 Penalized Regression (Lasso Regression) with Cross-Validation: LassoCV
    - L2 Penalized Regression (Ridge Regression) with Cross-Validation: RidgeCV
    - Cross-Validation: StratifiedKFold, RepeatedKFold, LeaveOneOut, KFold, model_selection.cross_validate, model_selection.cross_val_predict, model_selection.cross_val_score
    - Model Metrics (https://scikit-learn.org/stable/modules/classes.html#sklearn-metrics-metrics): accuracy_score, auc, f1_score, hamming_loss, precision_score, recall_score, roc_auc_score
- Decision Tree: DecisionTreeClassifier, DecisionTreeRegressor
- Bootstrap, Ensemble Methods
    - Bootstrap: bootstrapped (https://pypi.org/project/bootstrapped/)
    - Bagging: RandomForestClassifier, RandomForestRegressor
    - Boosting: AdaBoostClassifier, AdaBoostRegressor
- Support Vector Machines (https://scikit-learn.org/stable/modules/svm.html#svm): LinearSVC, LinearSVR
- Multiclass and Multilabel Classification (https://scikit-learn.org/stable/modules/classes.html#module-sklearn.multiclass)
    - One-vs-one Multiclass Strategy: OneVsOneClassifier
    - One-vs-the-rest (OvR) multiclass/multilabel strategy / OneVsRestClassifier
- Unsupervised Learning
    - K-means Clustering: KMeans
    - Hierarchical Clustering: scipy.cluster.hierarchy (not scikit-learn)
- Semisupervised Learning (https://scikit-learn.org/stable/modules/label_propagation.html)

### Git and GitHub

1. In the directory that where this jupyter notebook file locates in, init a Git repository.
2. Checkout a new branch called dev and commit the current notebook within this branch.
3. Merge the dev branch to the master branch (the default branch).
4. Create a temporary repository (just for practicing and you can delete it later) in GitHub. 
5. Push new changes in the master branch to the remote repository created in step 4.
6. Checkout the dev branch again and do some changes to your notebook, and then repeat step 3 and step 5.